version: '3'
services:
  user:
    build: ./user-svc
    ports:
      - "8001:8001"
    depends_on:
      - postgres
  order:
    build: ./order-svc
    ports:
      - "8002:8002"
    depends_on:
      - user
      - mysql
  notify:
    build: ./notification-svc
    ports:
      - "8003:8003"

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: pass
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass
